name: Release ARC Runner Images

# Revert to https://github.com/actions-runner-controller/releases#releases
# for details on why we use this approach
on:
  # We must do a trigger on a push: instead of a types: closed so GitHub Secrets
  # are available to the workflow run
  push:
    branches:
      - 'master'
    paths:
      - 'runner/VERSION'
      - '.github/workflows/arc-release-runners.yaml'

env:
  DOCKER_VERSION: 24.0.7

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-runners:
    name: Trigger Build and Push of Runner Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get runner version
        id: versions
        run: |
          runner_current_version="$(echo -n $(cat runner/VERSION | grep 'RUNNER_VERSION=' | cut -d '=' -f2))"
          container_hooks_current_version="$(echo -n $(cat runner/VERSION | grep 'RUNNER_CONTAINER_HOOKS_VERSION=' | cut -d '=' -f2))"
          echo runner_version=$runner_current_version >> $GITHUB_OUTPUT
          echo container_hooks_version=$container_hooks_current_version >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Versioned Tags
        uses: docker/build-push-action@v6
        with:
          context: ./runner
          file: ./runner/actions-runner.ubuntu-24.04.dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
            RUNNER_CONTAINER_HOOKS_VERSION=${{ env.CONTAINER_HOOKS_VERSION }}
          tags: |
            ghcr.io/erichorwath/actions-runner-controller/custom-u24-runner:v${{ env.RUNNER_VERSION }}-ubuntu-22.04
          cache-from: |
            type=gha,scope=sha-${{ github.sha }}
            type=gha,scope=${{ github.ref_name }}
            type=gha,scope=${{ github.base_ref || 'main' }}
            type=gha,scope=main
          cache-to: |
            type=gha,scope=sha-${{ github.sha }},mode=max
            type=gha,scope=${{ github.ref_name }},mode=max
